
server: Server.class
	java Server
Server.class: Server.java
	javac Server.java
replier: Replier.class
	java Replier
Replier.class: Replier.java
	javac Replier.java
clear:
	del *.class 
	del *~
